Mod 6 ober page
Modus-1/staff-frontend pull request #11
Opened 2022-12-15 13:31 UTC by rmzhen

2022-12-15 13:34 UTC, LokiTheShadySpirit approved these changes
Yippie I love sorting

2022-12-16 09:44 UTC, LokiTheShadySpirit approved these changes

2022-12-16 09:48 UTC, judahlit commented on src/App.js
> +        console.log(orderToUpdate);
console.log should be removed

2022-12-16 09:48 UTC, judahlit requested changes

2022-12-16 09:48 UTC, judahlit commented on src/pages/KitchenPage.js
> +      console.log("hello world")
console.log should be removed

2022-12-16 09:48 UTC, judahlit commented on src/pages/WaiterPage.js
> +    console.log(props.columns);
console.log should be removed

2022-12-16 09:48 UTC, judahlit commented on src/services/OrderWebSocketService.js
> +    console.log(order);
console.log should be removed

2022-12-16 09:58 UTC, rmzhen commented on src/pages/KitchenPage.js
> +      console.log("hello world")
Fixed

2022-12-16 09:59 UTC, rmzhen commented on src/pages/WaiterPage.js
> +    console.log(props.columns);
Fixed

2022-12-16 09:59 UTC, rmzhen commented on src/services/OrderWebSocketService.js
> +    console.log(order);
Fixed

2022-12-16 10:04 UTC, LukasJansen100 approved these changes

2022-12-16 10:10 UTC, judahlit approved these changes

2022-12-16 10:11 UTC, merged